import './globals.css'
import { Inter } from 'next/font/google'
import NavBar from '../components/NavBar'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css"></link>
      <head>
        <title>Harbour Booking</title>
        </head>
     
      <body className={inter.className}>
       <NavBar/>
      {children}
      </body>
      
    </html>
    
  )
}
